from django.contrib.auth.views import LogoutView
from django.http import JsonResponse
from django.urls import include, path

from . import ads_views, intelligence_views, media_views, prompt_views, sequence_views, views
from .onboarding import SignInView, setup
from .company_settings import company_settings, costs
from .performance_views import performance

engine_urls = [
    path("prompts/", prompt_views.prompt_library, name="prompt_library"),
    path("prompts/<uuid:prompt_id>/", prompt_views.prompt_detail, name="prompt_detail"),
    path("prompts/<uuid:prompt_id>/favorite/", prompt_views.prompt_favorite, name="prompt_favorite"),
    path("prompts/<uuid:prompt_id>/archive/", prompt_views.prompt_archive, name="prompt_archive"),
    path("prompts/<uuid:prompt_id>/restore/", prompt_views.prompt_restore, name="prompt_restore"),
    path("prompts/from-generation/<uuid:job_id>/", prompt_views.prompt_save_generation, name="prompt_save_generation"),
    path("intelligence/own/",performance,name="own_performance"),
    path("intelligence/ads/<int:ad_id>/detail/", ads_views.detail, name="ad_detail"),
    path("intelligence/ads/accounts/<int:account_id>/", ads_views.account_action, name="ad_account_action"),
    path("intelligence/ads/analyze/<int:ad_id>/", ads_views.analyze, name="ad_analyze"),
    path("runs/<uuid:run_id>/outcome/", ads_views.outcome, name="outcome"),
    path("settings/", company_settings, name="settings"),
    path("costs/", costs, name="costs"),
    path("sequences/", sequence_views.sequence_list, name="sequence_list"),
    path("sequences/<uuid:project_id>/", sequence_views.sequence_workspace, name="sequence_workspace"),
    path("sequences/<uuid:project_id>/plan/generate/", sequence_views.sequence_plan_generate, name="sequence_plan_generate"),
    path("sequences/<uuid:project_id>/plan/save/", sequence_views.sequence_plan_save, name="sequence_plan_save"),
    path("sequences/<uuid:project_id>/anchors/add-existing/", sequence_views.sequence_anchor_add_existing, name="sequence_anchor_add_existing"),
    path("sequences/<uuid:project_id>/anchors/add-upload/", sequence_views.sequence_anchor_add_upload, name="sequence_anchor_add_upload"),
    path("sequences/<uuid:project_id>/anchors/generate/", sequence_views.sequence_anchor_generate, name="sequence_anchor_generate_new"),
    path("sequences/<uuid:project_id>/anchors/<uuid:anchor_id>/lock/", sequence_views.sequence_anchor_lock, name="sequence_anchor_lock"),
    path("sequences/<uuid:project_id>/anchors/<uuid:anchor_id>/replace-existing/", sequence_views.sequence_anchor_replace_existing, name="sequence_anchor_replace_existing"),
    path("sequences/<uuid:project_id>/anchors/<uuid:anchor_id>/replace-upload/", sequence_views.sequence_anchor_replace_upload, name="sequence_anchor_replace_upload"),
    path("sequences/<uuid:project_id>/anchors/<uuid:anchor_id>/generate/", sequence_views.sequence_anchor_generate, name="sequence_anchor_generate"),
    path("sequences/<uuid:project_id>/clips/<uuid:clip_id>/prepare/", sequence_views.sequence_clip_prepare, name="sequence_clip_prepare"),
    path("sequences/<uuid:project_id>/clips/<uuid:clip_id>/versions/<uuid:version_id>/select/", sequence_views.sequence_clip_select, name="sequence_clip_select"),
    path("sequences/<uuid:project_id>/clips/<uuid:clip_id>/versions/<uuid:version_id>/cancel/", sequence_views.sequence_clip_cancel, name="sequence_clip_cancel"),
    path("sequences/<uuid:project_id>/anchors/<uuid:anchor_id>/revisions/<uuid:revision_id>/restore/", sequence_views.sequence_anchor_restore, name="sequence_anchor_restore"),
    path("sequences/<uuid:project_id>/anchor-targets/<uuid:target_id>/assets/<uuid:asset_id>/apply/", sequence_views.sequence_anchor_apply_generated, name="sequence_anchor_apply_generated"),
    path("media/", media_views.library, name="media_library"),
    path("media/new/", media_views.new_studio, name="media_new"),
    path("media/upload/", media_views.library_upload, name="media_library_upload"),
    path("media/<uuid:asset_id>/file/", media_views.asset_file, name="asset_file"),
    path("runs/<uuid:run_id>/media/", media_views.picker, name="media"),
    path("runs/<uuid:run_id>/media/upload/", media_views.upload, name="media_upload"),
    path("runs/<uuid:run_id>/media/generate/", media_views.generate_media, name="media_generate"),
    path("runs/<uuid:run_id>/media/jobs/<uuid:job_id>/", media_views.job_page, name="media_job"),
    path("runs/<uuid:run_id>/media/jobs/<uuid:job_id>/status/", media_views.job_status, name="media_job_status"),
    path("runs/<uuid:run_id>/media/jobs/<uuid:job_id>/refresh-provider/", media_views.refresh_provider_status, name="media_job_refresh_provider"),
    path("runs/<uuid:run_id>/media/jobs/<uuid:job_id>/start/", media_views.job_start, name="media_job_start"),
    path("runs/<uuid:run_id>/media/jobs/<uuid:job_id>/cancel/", media_views.cancel_generation, name="media_job_cancel"),
    path("runs/<uuid:run_id>/media/jobs/<uuid:job_id>/reset/", media_views.reset_job, name="media_job_reset"),
    path("runs/<uuid:run_id>/media/<uuid:asset_id>/use/", media_views.use_asset, name="media_use"),
    path("runs/<uuid:run_id>/media/<uuid:asset_id>/delete/", media_views.delete_asset, name="media_delete"),
    path("intelligence/", intelligence_views.intelligence, name="intelligence"),
    path("intelligence/refresh/", intelligence_views.refresh_imports, name="refresh_imports"),
    path("intelligence/accounts/<int:competitor_id>/", intelligence_views.competitor_action, name="competitor_action"),
    path("intelligence/analyze/<int:post_id>/", intelligence_views.analyze_signal, name="analyze_signal"),
    path("runs/<uuid:run_id>/reject/<int:idea_index>/", intelligence_views.reject_idea, name="reject_idea"),
    path("", views.home, name="home"),
    path("ideas/", views.ideas, name="ideas"),
    path("connect/", views.connect, name="connect"),
    path("runs/<uuid:run_id>/", views.review, name="review"),
    path("runs/<uuid:run_id>/draft/<int:idea_index>/", views.draft, name="draft"),
]
urlpatterns = [
    path("", views.index, name="dashboard"),
    path("setup/", setup, name="setup"),
    path("accounts/login/", SignInView.as_view(), name="login"),
    path("accounts/logout/", LogoutView.as_view(), name="logout"),
    path("health/", lambda request: JsonResponse({"status": "ok"})),
    path("webhooks/higgsfield/", media_views.higgsfield_webhook, name="higgsfield_webhook"),
    path("company/<uuid:workspace_id>/", include((engine_urls, "engine"))),
]
