import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
groups = {
    "text": [
        ("kinetic-words", "Kinetiska ord", "Ord tar plats ett i taget med rytmisk skalning."),
        ("line-reveal", "Radvis avsl\u00f6jande", "Rader glider fram bakom en gemensam mask."),
        ("letter-cascade", "Bokstavskaskad", "Bokst\u00e4ver landar med f\u00f6rskjuten timing."),
        ("typewriter", "Skrivmaskin", "Text skrivs fram tecken f\u00f6r tecken med mark\u00f6r."),
        ("tracking", "Bokstavsavst\u00e5nd", "Gles typografi samlas till en tydlig rubrik."),
        ("blur-reveal", "Fokus", "Text g\u00e5r fr\u00e5n oskarp till skarp."),
        ("mask-rise", "Maskerad uppg\u00e5ng", "Rubrik reser sig bakom en skarp baslinje."),
        ("brush-write", "Penseldrag", "Organiska penselband avsl\u00f6jar text."),
        ("outline-fill", "Kontur till fyllning", "Konturtypografi fylls stegvis med f\u00e4rg."),
        ("word-highlight", "Markerade ord", "En mark\u00f6r f\u00f6ljer rubrikens ord."),
        ("split-flap", "Bl\u00e4ddrande rubrik", "Tv\u00e5delade bokstavspaneler v\u00e4nder fram budskapet."),
        ("number-emphasis", "Siffra i fokus", "En stor siffra f\u00f6rankrar en kort rubrik."),
    ],
    "data": [
        ("counter", "R\u00e4knare", "Heltal r\u00e4knas upp med lugn inbromsning."),
        ("currency", "Belopp", "Valutabelopp med svensk tusentalsgruppering."),
        ("percentage", "Procent", "Procenttal kombinerat med en cirkul\u00e4r indikator."),
        ("ranking", "Topplista", "Rangordnade rader presenteras i ordning."),
        ("bars", "Stapeldiagram", "J\u00e4mf\u00f6rbara v\u00e4rden v\u00e4xer fr\u00e5n samma nollpunkt."),
        ("comparison", "J\u00e4mf\u00f6relse", "Tv\u00e5 v\u00e4rden visas sida vid sida."),
        ("donut", "F\u00f6rdelning", "Andelar blir ett tydligt ringdiagram."),
        ("timeline", "Tidslinje", "Milstolpar framtr\u00e4der l\u00e4ngs en sammanh\u00e4ngande linje."),
        ("stat-wall", "Nyckeltalsv\u00e4gg", "Flera nyckeltal presenteras med konsekvent hierarki."),
        ("sparkline", "Trendlinje", "En obruten linje visar en serie v\u00e4rden."),
    ],
    "scene": [
        ("footage", "Ditt material", "Hela bilden eller klippet, utan beskärning, filter eller klippljud."),
        ("hero", "Titel", "Stor rubrik med liten inledning och tydlig hierarki."),
        ("quote", "Citat", "Ett citat med tydligt avs\u00e4ndarnamn."),
        ("product", "Produkt", "En verklig produktbild med kort f\u00f6rklaring."),
        ("offer", "Erbjudande", "Ett belopp eller erbjudande och en tydlig uppmaning."),
        ("list", "Lista", "En l\u00e4ttl\u00e4st lista med stegvis fokus."),
        ("logo-sting", "Logotypintro", "Den riktiga logotypen landar med en diskret accent."),
        ("end-card", "Slutbild", "Logotyp, slutbudskap och en tydlig uppmaning."),
        ("cta", "Uppmaning", "Ett koncentrerat budskap med tydlig n\u00e4sta handling."),
        ("recap", "Sammanfattning", "Flera tidigare nyckeltal samlas till en helhetsbild."),
        ("countdown", "Nedr\u00e4kning", "En stor siffra r\u00e4knar ned till ett budskap."),
        (
            "before-after",
            "F\u00f6re och efter",
            "Tv\u00e5 verkliga bilder j\u00e4mf\u00f6rs med en r\u00f6rlig delning.",
        ),
        ("announcement", "Nyhet", "Ett tydligt nyhetsband med rubrik och beskrivning."),
        ("testimonial", "Kundber\u00e4ttelse", "Citat, avs\u00e4ndare och valfri portr\u00e4ttbild."),
        ("device", "Appvisning", "En riktig sk\u00e4rmbild visas i en neutral mobilram."),
        ("spotlight", "Anl\u00e4ggning i fokus", "Stor verklig bild med plats och presentation."),
        ("steps", "S\u00e5 fungerar det", "Tre numrerade steg med gemensam visuell tr\u00e5d."),
        ("split-media", "Delad bild och text", "En bildyta och en separat redaktionell texthalva."),
        ("mosaic", "Bildmosaik", "Tv\u00e5 bilder med f\u00f6rskjuten inramning och rubrik."),
        ("lottie-mark", "Vektorm\u00e4rke", "Ett registrerat Lottie-m\u00e4rke ritas upp bildruta f\u00f6r bildruta."),
        ("perspective-stack", "Perspektiv", "Texter eller bilder ordnas med kontrollerat CSS-perspektiv."),
    ],
    "transition": [
        ("cut", "Klipp", "Direkt byte utan \u00f6verlagring."),
        ("fade", "\u00d6vertoning", "Mjuk \u00f6vertoning mellan tv\u00e5 scener."),
        ("wipe", "Svep", "N\u00e4sta scen avsl\u00f6jas med en horisontell mask."),
        ("push", "Skjut", "B\u00e5da scenerna f\u00f6rflyttas tillsammans."),
        ("whip", "Sn\u00e4rt", "Snabb sidr\u00f6relse med kort r\u00f6relseosk\u00e4rpa."),
        ("zoom", "Zoom igenom", "En scen n\u00e4rmar sig medan n\u00e4sta tar \u00f6ver."),
        ("iris", "Iris", "En cirkul\u00e4r \u00f6ppning avsl\u00f6jar n\u00e4sta scen."),
        ("diagonal", "Diagonal", "En diagonal mask sk\u00e4r \u00f6ver bildytan."),
        ("blinds", "Lameller", "Vertikala f\u00e4lt \u00f6ppnas i turordning."),
        ("split", "Delning", "Tv\u00e5 halvor \u00f6ppnas fr\u00e5n mitten."),
        ("brush", "Penselsvep", "Oregelbundna band avsl\u00f6jar n\u00e4sta scen."),
        ("blur", "Osk\u00e4rpa", "Scener byts vid en kort fokuserad osk\u00e4rpa."),
        ("flash", "Ljusblixt", "En enda kort ljus\u00f6verg\u00e5ng, utan stroboskop."),
    ],
    "background": [
        ("solid", "Enf\u00e4rgat", "En lugn yta fr\u00e5n valt varum\u00e4rke."),
        ("radial", "Radialt ljus", "Mjukt ljus med l\u00e5ngsam f\u00f6rflyttning."),
        ("mesh", "F\u00e4rgf\u00e4lt", "Tv\u00e5 breda f\u00e4rgf\u00e4lt r\u00f6r sig lugnt."),
        ("grid", "Rutn\u00e4t", "Tunnt rutn\u00e4t med f\u00f6rskjutning."),
        ("orbits", "Banor", "Koncentriska linjer roterar runt en gemensam punkt."),
        ("particles", "Partiklar", "Glesa deterministiska partiklar driver \u00f6ver ytan."),
        ("rays", "Str\u00e5lar", "Breda str\u00e5lar r\u00f6r sig bakom inneh\u00e5llet."),
        ("waves", "V\u00e5gor", "Lager av SVG-kurvor skapar lugn r\u00f6relse."),
        ("topography", "H\u00f6jdkurvor", "Linjer inspirerade av en banas topografi."),
        ("checker", "Schackm\u00f6nster", "Ett diskret grafiskt rutm\u00f6nster f\u00f6rskjuts."),
    ],
    "effect": [
        ("grain", "Korn", "L\u00e4tt deterministisk filmstruktur."),
        ("vignette", "Vinjett", "Diskret m\u00f6rkare kanter koncentrerar blicken."),
        ("glow", "Gl\u00f6d", "Ett mjukt accentljus bakom fokusobjektet."),
        ("shadow", "Djup", "Inneh\u00e5llet f\u00e5r en kontrollerad skugga."),
        ("parallax", "Parallax", "Inneh\u00e5ll och bakgrund r\u00f6r sig i olika tempo."),
        ("glitch", "Grafisk f\u00f6rskjutning", "En kort f\u00f6rskjutning vid introduktionen."),
        ("scanline", "Skanningslinje", "En tunn ljuslinje passerar en g\u00e5ng."),
        ("duotone", "Tv\u00e5ton", "Media f\u00e4rgas med varum\u00e4rkets tv\u00e5 toner."),
        ("frame", "Inramning", "En tunn ram ritas runt inneh\u00e5llet."),
        ("svg-path", "Ritad bana", "En SVG-bana ritas med synkroniserad mark\u00f6r."),
    ],
    "audio": [
        ("tick", "R\u00e4knartick", "Kort, mjukt tick med begr\u00e4nsad frekvens."),
        ("impact", "Impact", "Kort basbetoning f\u00f6r ett viktigt avsl\u00f6jande."),
        ("whoosh", "Svepljud", "Kort filtrerat brus f\u00f6ljer en \u00f6verg\u00e5ng."),
        ("rise", "Stegring", "En mjuk upp\u00e5tg\u00e5ende ton bygger f\u00f6rv\u00e4ntan."),
        ("sting", "Logotypljud", "Tre korta toner f\u00f6r en avslutande logotyp."),
        ("pluck", "Plock", "En varm plockton markerar ett steg."),
        ("pulse", "Puls", "En d\u00e4mpad rytmisk puls."),
        ("chime", "Klockton", "En ljus, l\u00e5ngsamt avklingande ton."),
        ("bed", "Musikb\u00e4dd", "Egen genererad diskret tonb\u00e4dd utan externt ljudmaterial."),
    ],
}
templates = [
    ("sequence-film", "Färdig sekvens", "Sätt ihop egna bilder eller granskade klipp till en film.", "sequence", [], ["footage", "end-card"]),
    (
        "monthly-wrapped",
        "Monthly Wrapped",
        "September, m\u00e5nadens siffror och ett starkt avslut.",
        "data",
        ["month", "count", "total", "area"],
        ["hero", "counter", "currency", "ranking", "end-card"],
    ),
    (
        "kpi-recap",
        "KPI Recap",
        "Sammanfatta flera nyckeltal i en video.",
        "data",
        ["headline", "items"],
        ["hero", "stat-wall", "bars", "cta"],
    ),
    (
        "product-offer",
        "Produkt och erbjudande",
        "Visa produkten, v\u00e4rdet och n\u00e4sta steg.",
        "ads",
        ["headline", "body", "cta"],
        ["product", "offer", "cta"],
    ),
    (
        "facility-spotlight",
        "Golfklubb i fokus",
        "Presentera en klubb eller anl\u00e4ggning med egna bilder.",
        "golf",
        ["headline", "body", "asset_id"],
        ["spotlight", "split-media", "cta"],
    ),
    (
        "friskvard-explainer",
        "S\u00e5 fungerar friskv\u00e5rd",
        "F\u00f6rklara ett enkelt fl\u00f6de i tre steg.",
        "golf",
        ["headline", "items", "cta"],
        ["hero", "steps", "cta"],
    ),
    (
        "gift-card-promo",
        "Ge bort golf",
        "Presentera ett riktigt presentkort med ett personligt budskap.",
        "promo",
        ["headline", "body", "cta"],
        ["product", "quote", "cta"],
    ),
    (
        "new-partner",
        "Ny partner",
        "V\u00e4lkomna en ny ansluten anl\u00e4ggning.",
        "golf",
        ["headline", "body"],
        ["announcement", "spotlight", "end-card"],
    ),
    (
        "product-launch",
        "Produktlansering",
        "Fr\u00e5n nyhet till produkt och handling.",
        "product",
        ["headline", "body", "cta"],
        ["announcement", "product", "perspective-stack", "cta"],
    ),
    (
        "feature-announcement",
        "Ny funktion",
        "Visa en funktion med riktig sk\u00e4rmbild.",
        "product",
        ["headline", "body", "asset_id"],
        ["kinetic-words", "device", "steps", "cta"],
    ),
    (
        "social-promo",
        "Social kampanj",
        "Ett kort budskap med tydlig rytm.",
        "social",
        ["headline", "body", "cta"],
        ["kinetic-words", "offer", "cta"],
    ),
    (
        "kinetic-text",
        "Kinetisk text",
        "L\u00e5t orden vara huvudpersonen.",
        "typography",
        ["headline", "body"],
        ["kinetic-words", "typewriter", "word-highlight", "end-card"],
    ),
    (
        "quote-testimonial",
        "Citat och omd\u00f6me",
        "Lyft en verklig kundr\u00f6st.",
        "social",
        ["headline", "attribution"],
        ["testimonial", "quote", "end-card"],
    ),
    (
        "top-three",
        "Topp 3",
        "Presentera en verifierad rangordning.",
        "data",
        ["headline", "items"],
        ["hero", "ranking", "recap", "cta"],
    ),
    (
        "before-after-story",
        "F\u00f6re och efter",
        "Visa skillnaden med tv\u00e5 verkliga bilder.",
        "product",
        ["headline", "asset_id", "secondary_asset_id"],
        ["hero", "before-after", "cta"],
    ),
    (
        "logo-end-card",
        "Logotyp och avslut",
        "Ett koncentrerat intro eller avslut.",
        "end-cards",
        ["headline", "cta"],
        ["logo-sting", "end-card"],
    ),
    (
        "custom-storyboard",
        "Egen storyboard",
        "B\u00f6rja med scener och bygg en egen ber\u00e4ttelse.",
        "social",
        ["headline"],
        ["hero", "cta"],
    ),
]
items = []
for kind, rows in groups.items():
    for id, name, desc in rows:
        items.append(
            dict(
                id=id,
                name=name,
                description=desc,
                kind=kind,
                category=kind,
                tags=[id, kind, name.lower()],
                version=1,
                aspect_ratios=["9:16", "1:1", "16:9"],
                required_props=["headline"] if kind in ("text", "data", "scene") else [],
                optional_props=[
                    "body",
                    "value",
                    "unit",
                    "items",
                    "asset_id",
                    "secondary_asset_id",
                    "cta",
                    "attribution",
                ]
                if kind in ("text", "data", "scene")
                else [],
                source="content-engine/original-motion",
                license="Repository LICENSE (original implementation)",
                status="candidate",
                preview=None,
            )
        )
for id, name, desc, category, required, scenes in templates:
    items.append(
        dict(
            id=id,
            name=name,
            description=desc,
            kind="template",
            category=category,
            tags=[id, category, name.lower()] + scenes,
            version=1,
            aspect_ratios=["9:16", "1:1", "16:9"],
            required_props=required,
            optional_props=["end_card_asset_id", "cta"] if id == "monthly-wrapped" else ["asset_id", "secondary_asset_id", "end_card_asset_id", "cta", "attribution"],
            source="content-engine/original-templates; HyperFrames-informed pacing",
            license="Repository LICENSE (original implementation)",
            status="candidate",
            preview=None,
            scene_components=scenes,
            typical_seconds=24 if id == "monthly-wrapped" else len(scenes) * 4,
        )
    )
assert len(items) == len({x["id"] for x in items})
path = ROOT / "engine/motion/catalog.json"
path.write_text(json.dumps({"version": 1, "items": items}, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
print(
    "Catalogue definitions:",
    len(items),
    "items;",
    len(templates),
    "templates. All candidate until rendered preview verification.",
)
