# Generated by Django 5.2.17 on 2026-09-07 16:29

import apps.common.encryption
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='brandcontext',
            name='postiz_channels',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='brandcontext',
            name='postiz_key',
            field=apps.common.encryption.EncryptedTextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='contentrun',
            name='delivery_result',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='contentrun',
            name='delivery_status',
            field=models.CharField(default='draft', max_length=20),
        ),
    ]
