# Generated by Django 5.2.17 on 2026-09-08 05:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0002_setup_lock'),
    ]

    operations = [
        migrations.CreateModel(
            name='Competitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('username', models.CharField(max_length=30)),
                ('active', models.BooleanField(default=True)),
                ('last_success_at', models.DateTimeField(null=True)),
                ('last_error', models.CharField(blank=True, max_length=500)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competitors', to='engine.company')),
            ],
        ),
        migrations.CreateModel(
            name='CompetitorImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor', models.CharField(max_length=100)),
                ('actor_run_id', models.CharField(max_length=100, null=True, unique=True)),
                ('dataset_id', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(default='starting', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(null=True)),
                ('cost_usd', models.DecimalField(decimal_places=6, max_digits=12, null=True)),
                ('item_count', models.PositiveIntegerField(default=0)),
                ('skipped_count', models.PositiveIntegerField(default=0)),
                ('requested_limit', models.PositiveIntegerField(default=100)),
                ('error', models.CharField(blank=True, max_length=500)),
                ('competitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imports', to='engine.competitor')),
                ('fallback_of', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='engine.competitorimport')),
            ],
        ),
        migrations.CreateModel(
            name='CompetitorPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shortcode', models.CharField(max_length=100)),
                ('instagram_id', models.CharField(blank=True, max_length=100)),
                ('url', models.URLField(max_length=500)),
                ('published_at', models.DateTimeField(db_index=True)),
                ('caption', models.TextField(blank=True)),
                ('format', models.CharField(choices=[('image', 'Bild'), ('carousel', 'Carousel'), ('reel', 'Reel/video')], max_length=20)),
                ('duration_seconds', models.FloatField(null=True)),
                ('slide_count', models.PositiveSmallIntegerField(null=True)),
                ('classification', models.JSONField(default=dict)),
                ('classification_hash', models.CharField(blank=True, max_length=64)),
                ('classified_at', models.DateTimeField(null=True)),
                ('classifier_model', models.CharField(blank=True, max_length=100)),
                ('competitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='engine.competitor')),
            ],
        ),
        migrations.CreateModel(
            name='CompetitorSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observed_at', models.DateTimeField(db_index=True)),
                ('likes', models.BigIntegerField(null=True)),
                ('comments', models.BigIntegerField(null=True)),
                ('views', models.BigIntegerField(null=True)),
                ('view_metric', models.CharField(blank=True, max_length=30)),
                ('import_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='engine.competitorimport')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='engine.competitorpost')),
            ],
            options={
                'ordering': ['observed_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ContentEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idea_index', models.PositiveSmallIntegerField(null=True)),
                ('action', models.CharField(max_length=30)),
                ('data', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='engine.contentrun')),
            ],
        ),
        migrations.AddConstraint(
            model_name='competitor',
            constraint=models.UniqueConstraint(fields=('company', 'username'), name='unique_company_competitor'),
        ),
        migrations.AddConstraint(
            model_name='competitorpost',
            constraint=models.UniqueConstraint(fields=('competitor', 'shortcode'), name='unique_competitor_post'),
        ),
        migrations.AddConstraint(
            model_name='competitorsnapshot',
            constraint=models.UniqueConstraint(fields=('post', 'import_run'), name='unique_post_observation'),
        ),
    ]
