# Generated by Django 5.2.17 on 2026-09-08 18:20

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0003_competitor_competitorimport_competitorpost_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaAsset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('image', 'Bild'), ('video', 'Video')], max_length=10)),
                ('origin', models.CharField(choices=[('uploaded', 'Uppladdad'), ('generated', 'AI-genererad')], max_length=10)),
                ('provider', models.CharField(max_length=20)),
                ('storage_backend', models.CharField(max_length=10)),
                ('storage_key', models.CharField(max_length=300)),
                ('mime_type', models.CharField(max_length=80)),
                ('byte_size', models.PositiveBigIntegerField()),
                ('width', models.PositiveIntegerField(null=True)),
                ('height', models.PositiveIntegerField(null=True)),
                ('duration_seconds', models.FloatField(null=True)),
                ('alt_text', models.CharField(blank=True, max_length=500)),
                ('brief', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(null=True)),
                ('used_at', models.DateTimeField(null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_assets', to='engine.company')),
            ],
        ),
        migrations.AddField(
            model_name='contentrun',
            name='media_asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='content_runs', to='engine.mediaasset'),
        ),
        migrations.CreateModel(
            name='MediaGeneration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(max_length=10)),
                ('provider', models.CharField(max_length=20)),
                ('brief', models.TextField()),
                ('prompt', models.TextField()),
                ('parameters', models.JSONField(default=dict)),
                ('provider_id', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(default='queued', max_length=20)),
                ('error', models.CharField(blank=True, max_length=500)),
                ('usage', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_jobs', to='engine.contentrun')),
                ('source_asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='variations', to='engine.mediaasset')),
            ],
        ),
        migrations.AddField(
            model_name='mediaasset',
            name='generation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets', to='engine.mediageneration'),
        ),
    ]
