# Generated by Django 5.2.17 on 2026-09-08 23:27

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0004_mediaasset_contentrun_media_asset_mediageneration_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('day', models.DateField(unique=True)),
                ('status', models.CharField(default='running', max_length=15)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(null=True)),
                ('lease_token', models.UUIDField(null=True)),
                ('lease_until', models.DateTimeField(null=True)),
                ('summary', models.JSONField(default=dict)),
            ],
        ),
        migrations.AddField(
            model_name='company',
            name='official_logo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='official_for', to='engine.mediaasset'),
        ),
        migrations.AddField(
            model_name='mediaasset',
            name='generation_base_key',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='mediaasset',
            name='purpose',
            field=models.CharField(choices=[('content', 'Innehåll'), ('logo', 'Logga')], default='content', max_length=10),
        ),
        migrations.AddField(
            model_name='mediaasset',
            name='sha256',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='mediageneration',
            name='logo_asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='logo_generations', to='engine.mediaasset'),
        ),
        migrations.CreateModel(
            name='DailyStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(max_length=60)),
                ('version', models.CharField(default='v1', max_length=30)),
                ('key', models.CharField(max_length=160)),
                ('status', models.CharField(default='pending', max_length=15)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('started_at', models.DateTimeField(null=True)),
                ('finished_at', models.DateTimeField(null=True)),
                ('message', models.CharField(blank=True, max_length=500)),
                ('result', models.JSONField(default=dict)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_steps', to='engine.company')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='engine.dailyrun')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('run', 'company', 'stage', 'version', 'key'), name='unique_daily_work')],
            },
        ),
    ]
