# Generated by Django 5.2.17 on 2026-09-09 10:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0005_dailyrun_company_official_logo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScrapeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=64, unique=True)),
                ('actor', models.CharField(max_length=100)),
                ('mode', models.CharField(max_length=20)),
                ('inputs', models.JSONField(default=dict)),
                ('status', models.CharField(default='starting', max_length=20)),
                ('actor_run_id', models.CharField(max_length=100, null=True, unique=True)),
                ('dataset_id', models.CharField(blank=True, max_length=100)),
                ('max_cost_usd', models.DecimalField(decimal_places=4, max_digits=10)),
                ('cost_usd', models.DecimalField(decimal_places=6, max_digits=12, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(null=True)),
                ('result', models.JSONField(default=dict)),
            ],
        ),
        migrations.AddField(
            model_name='competitorimport',
            name='sync_mode',
            field=models.CharField(default='discovery', max_length=20),
        ),
        migrations.AddField(
            model_name='contentrun',
            name='channel',
            field=models.CharField(choices=[('organic', 'Organiskt'), ('paid', 'Annonser')], default='organic', max_length=10),
        ),
        migrations.CreateModel(
            name='AdAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('page_url', models.URLField(max_length=500)),
                ('page_id', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(default='ALL', max_length=3)),
                ('active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ad_accounts', to='engine.company')),
            ],
        ),
        migrations.CreateModel(
            name='CompetitorAd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=100)),
                ('creative', models.JSONField(default=dict)),
                ('creative_hash', models.CharField(max_length=64)),
                ('classification', models.JSONField(default=dict)),
                ('classification_hash', models.CharField(blank=True, max_length=64)),
                ('first_seen_at', models.DateTimeField()),
                ('last_seen_at', models.DateTimeField()),
                ('start_date', models.DateField(null=True)),
                ('end_date', models.DateField(null=True)),
                ('is_active', models.BooleanField(null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ads', to='engine.adaccount')),
            ],
        ),
        migrations.CreateModel(
            name='LearningModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(max_length=10)),
                ('version', models.CharField(max_length=64)),
                ('target', models.CharField(max_length=60)),
                ('mode', models.CharField(default='shadow', max_length=15)),
                ('trained_at', models.DateTimeField(auto_now_add=True)),
                ('training_cutoff', models.DateTimeField()),
                ('artifact', models.JSONField(default=dict)),
                ('evaluation', models.JSONField(default=dict)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='engine.company')),
            ],
        ),
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idea_index', models.PositiveSmallIntegerField()),
                ('channel', models.CharField(max_length=10)),
                ('features', models.JSONField()),
                ('feature_version', models.CharField(max_length=40)),
                ('model_version', models.CharField(max_length=64)),
                ('value', models.FloatField(null=True)),
                ('target', models.CharField(max_length=60)),
                ('mode', models.CharField(default='shadow', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('model', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='engine.learningmodel')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to='engine.contentrun')),
            ],
        ),
        migrations.CreateModel(
            name='OwnOutcome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=60)),
                ('external_id', models.CharField(max_length=200)),
                ('published_at', models.DateTimeField()),
                ('window_end', models.DateTimeField()),
                ('observed_at', models.DateTimeField()),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('metrics', models.JSONField()),
                ('label', models.FloatField()),
                ('evidence', models.URLField(max_length=1000)),
                ('prediction', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='outcomes', to='engine.prediction')),
            ],
        ),
        migrations.CreateModel(
            name='AdObservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observed_at', models.DateTimeField()),
                ('data', models.JSONField(default=dict)),
                ('ad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observations', to='engine.competitorad')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='engine.scraperequest')),
            ],
        ),
        migrations.AddField(
            model_name='competitorimport',
            name='scrape_request',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='engine.scraperequest'),
        ),
        migrations.CreateModel(
            name='ScraperState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=30)),
                ('external_key', models.CharField(max_length=200)),
                ('backfill_attempted_at', models.DateTimeField(null=True)),
                ('watermark', models.DateTimeField(null=True)),
                ('last_refresh_at', models.DateTimeField(null=True)),
                ('next_attempt_at', models.DateTimeField(null=True)),
                ('coverage', models.CharField(default='uninitialized', max_length=30)),
                ('details', models.JSONField(default=dict)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='engine.company')),
            ],
        ),
        migrations.AddField(
            model_name='scraperequest',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='engine.scraperstate'),
        ),
        migrations.AddField(
            model_name='adaccount',
            name='sync',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='engine.scraperstate'),
        ),
        migrations.CreateModel(
            name='AnalysisMemo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=64)),
                ('status', models.CharField(default='started', max_length=20)),
                ('model', models.CharField(max_length=100)),
                ('result', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='engine.company')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('company', 'key'), name='unique_paid_analysis')],
            },
        ),
        migrations.AddConstraint(
            model_name='competitorad',
            constraint=models.UniqueConstraint(fields=('account', 'external_id'), name='unique_account_ad'),
        ),
        migrations.AddConstraint(
            model_name='learningmodel',
            constraint=models.UniqueConstraint(fields=('company', 'channel', 'version'), name='unique_learning_model'),
        ),
        migrations.AddConstraint(
            model_name='prediction',
            constraint=models.UniqueConstraint(fields=('run', 'idea_index', 'model_version'), name='unique_idea_prediction'),
        ),
        migrations.AddConstraint(
            model_name='ownoutcome',
            constraint=models.UniqueConstraint(fields=('prediction', 'source', 'external_id', 'window_end'), name='unique_own_outcome'),
        ),
        migrations.AddConstraint(
            model_name='adobservation',
            constraint=models.UniqueConstraint(fields=('ad', 'request'), name='unique_ad_observation'),
        ),
        migrations.AddConstraint(
            model_name='scraperstate',
            constraint=models.UniqueConstraint(fields=('company', 'source', 'external_key'), name='unique_scraper_source'),
        ),
        migrations.AddConstraint(
            model_name='adaccount',
            constraint=models.UniqueConstraint(fields=('company', 'page_url', 'country'), name='unique_ad_account'),
        ),
    ]
