# Generated by Django 5.2.17 on 2026-09-09 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0006_scraperequest_competitorimport_sync_mode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adaccount',
            name='country',
            field=models.CharField(default='SE', max_length=3),
        ),
    ]
