# Generated by Django 5.2.17 on 2026-09-09 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0007_alter_adaccount_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysismemo',
            name='attempts',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='analysismemo',
            name='last_attempt_at',
            field=models.DateTimeField(null=True),
        ),
    ]
