# Generated by Django 5.2.17 on 2026-09-09 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0008_analysismemo_attempts_analysismemo_last_attempt_at'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='adaccount',
            constraint=models.UniqueConstraint(condition=models.Q(('page_id', ''), _negated=True), fields=('company', 'page_id', 'country'), name='unique_ad_page_country'),
        ),
    ]
