# Generated by Django 5.2.17 on 2026-09-09 17:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0009_adaccount_unique_ad_page_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysismemo',
            name='scrape_request',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='analysis_memos', to='engine.scraperequest'),
        ),
    ]
