# Generated by Django 5.2.17 on 2026-09-09 17:23

import django.db.models.deletion
from django.db import migrations, models


def preserve_targets(apps, schema_editor):
    Outcome = apps.get_model("engine", "OwnOutcome")
    for outcome in Outcome.objects.filter(target="").select_related("prediction").iterator():
        outcome.target = outcome.prediction.target
        outcome.save(update_fields=["target"])


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0010_analysismemo_scrape_request'),
    ]

    operations = [
        migrations.CreateModel(
            name='OwnPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postiz_id', models.CharField(max_length=100)),
                ('integration_id', models.CharField(max_length=100)),
                ('release_id', models.CharField(blank=True, max_length=200)),
                ('platform', models.CharField(max_length=30)),
                ('format', models.CharField(default='unknown', max_length=30)),
                ('caption', models.TextField(blank=True)),
                ('url', models.URLField(blank=True, max_length=2000)),
                ('published_at', models.DateTimeField()),
                ('next_check_at', models.DateTimeField(null=True)),
                ('finalized_at', models.DateTimeField(null=True)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('last_error', models.CharField(blank=True, max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='OwnSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observed_at', models.DateTimeField()),
                ('source_day', models.DateField()),
                ('metrics', models.JSONField()),
                ('raw', models.JSONField()),
                ('contract', models.CharField(default='postiz-current-totals-v1', max_length=60)),
                ('baseline', models.JSONField(default=dict)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='ownoutcome',
            name='unique_own_outcome',
        ),
        migrations.AddField(
            model_name='ownoutcome',
            name='platform',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='ownoutcome',
            name='target',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='ownpost',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='own_posts', to='engine.company'),
        ),
        migrations.AddField(
            model_name='ownpost',
            name='run',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='own_posts', to='engine.contentrun'),
        ),
        migrations.AddField(
            model_name='ownsnapshot',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='engine.ownpost'),
        ),
        migrations.AddField(
            model_name='ownoutcome',
            name='snapshot',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='engine.ownsnapshot'),
        ),
        migrations.AddConstraint(
            model_name='ownoutcome',
            constraint=models.UniqueConstraint(fields=('prediction', 'source', 'target', 'external_id', 'window_end'), name='unique_own_outcome_target'),
        ),
        migrations.AddConstraint(
            model_name='ownpost',
            constraint=models.UniqueConstraint(fields=('company', 'integration_id', 'postiz_id'), name='unique_own_post'),
        ),
        migrations.AddConstraint(
            model_name='ownpost',
            constraint=models.UniqueConstraint(condition=models.Q(('release_id', ''), _negated=True), fields=('company', 'integration_id', 'release_id'), name='unique_own_release'),
        ),
        migrations.AddConstraint(
            model_name='ownsnapshot',
            constraint=models.UniqueConstraint(fields=('post', 'source_day', 'contract'), name='unique_own_snapshot_day'),
        ),
        migrations.RunPython(preserve_targets, migrations.RunPython.noop),
    ]
