# Generated by Django 5.2.17 on 2026-09-09 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0011_ownpost_ownsnapshot_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='ownsnapshot',
            name='unique_own_snapshot_day',
        ),
        migrations.AddField(
            model_name='ownsnapshot',
            name='checkpoint',
            field=models.CharField(default='daily', max_length=10),
        ),
        migrations.AddConstraint(
            model_name='ownsnapshot',
            constraint=models.UniqueConstraint(fields=('post', 'source_day', 'contract', 'checkpoint'), name='unique_own_snapshot_checkpoint'),
        ),
    ]
