# Generated by Django 5.2.17 on 2026-09-21 15:28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0012_remove_ownsnapshot_unique_own_snapshot_day_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PromptEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('original_text', models.TextField(editable=False)),
                ('original_hash', models.CharField(editable=False, max_length=64)),
                ('text', models.TextField()),
                ('title', models.CharField(blank=True, max_length=160)),
                ('metadata', models.JSONField(default=dict)),
                ('source_url', models.URLField(blank=True, max_length=2000)),
                ('notes', models.TextField(blank=True)),
                ('origin', models.CharField(default='manual', max_length=20)),
                ('favorite', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prompts', to='engine.company')),
                ('generation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='saved_prompts', to='engine.mediageneration')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PromptTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=80)),
                ('prompt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terms', to='engine.promptentry')),
            ],
        ),
        migrations.AddIndex(
            model_name='promptentry',
            index=models.Index(fields=['company', 'archived_at', '-created_at'], name='prompt_company_recent_idx'),
        ),
        migrations.AddConstraint(
            model_name='promptentry',
            constraint=models.UniqueConstraint(fields=('company', 'original_hash'), name='unique_company_prompt_original'),
        ),
        migrations.AddIndex(
            model_name='promptterm',
            index=models.Index(fields=['value', 'prompt'], name='prompt_term_lookup_idx'),
        ),
        migrations.AddConstraint(
            model_name='promptterm',
            constraint=models.UniqueConstraint(fields=('prompt', 'value'), name='unique_prompt_term'),
        ),
    ]
