# Generated by Django 5.2.17 on 2026-09-30 11:17

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("engine", "0020_sequence_ai_anchors_g2"),
    ]

    operations = [
        migrations.CreateModel(
            name="MotionKeyframe",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("scene_id", models.CharField(max_length=64)),
                ("frame", models.PositiveIntegerField()),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="motion_storyboards",
                        to="engine.mediaasset",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MotionRender",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("mode", models.CharField(choices=[("preview", "Preview"), ("final", "Final")], max_length=10)),
                ("progress", models.FloatField(default=0)),
                ("attempts", models.PositiveSmallIntegerField(default=0)),
                ("lease_token", models.UUIDField(blank=True, null=True)),
                ("lease_expires_at", models.DateTimeField(blank=True, null=True)),
                ("diagnostics", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "generation",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="motion_render",
                        to="engine.mediageneration",
                    ),
                ),
                (
                    "keyframes",
                    models.ManyToManyField(
                        related_name="motion_keyframes", through="engine.MotionKeyframe", to="engine.mediaasset"
                    ),
                ),
                (
                    "output_asset",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="motion_outputs",
                        to="engine.mediaasset",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MotionProject",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=160)),
                ("current_revision", models.PositiveIntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name="motion_projects", to="engine.company"
                    ),
                ),
                (
                    "run",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="motion_project",
                        to="engine.contentrun",
                    ),
                ),
                (
                    "approved_preview",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="engine.motionrender",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="motionkeyframe",
            name="render",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="storyboard", to="engine.motionrender"
            ),
        ),
        migrations.CreateModel(
            name="MotionRevision",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("number", models.PositiveIntegerField()),
                ("spec", models.JSONField()),
                ("spec_hash", models.CharField(max_length=64)),
                ("brand", models.JSONField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="revisions", to="engine.motionproject"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="motionrender",
            name="revision",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, related_name="renders", to="engine.motionrevision"
            ),
        ),
        migrations.CreateModel(
            name="MotionAssetReference",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("sha256", models.CharField(max_length=64)),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="motion_references",
                        to="engine.mediaasset",
                    ),
                ),
                (
                    "revision",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="asset_references",
                        to="engine.motionrevision",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="motionkeyframe",
            constraint=models.UniqueConstraint(fields=("render", "scene_id"), name="motion_keyframe_scene_unique"),
        ),
        migrations.AddConstraint(
            model_name="motionrevision",
            constraint=models.UniqueConstraint(fields=("project", "number"), name="motion_revision_number_unique"),
        ),
        migrations.AddIndex(
            model_name="motionrender",
            index=models.Index(fields=["lease_expires_at", "created_at"], name="motion_lease_idx"),
        ),
        migrations.AddConstraint(
            model_name="motionassetreference",
            constraint=models.UniqueConstraint(fields=("revision", "asset"), name="motion_revision_asset_unique"),
        ),
    ]
