# Generated by Django 5.2.17 on 2026-09-30 11:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("engine", "0021_motion_engine"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mediaasset",
            name="kind",
            field=models.CharField(choices=[("image", "Bild"), ("video", "Video"), ("audio", "Ljud")], max_length=10),
        ),
    ]
