# Generated by Django 5.2.17 on 2026-09-30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("engine", "0022_alter_mediaasset_kind"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="market_intelligence_enabled",
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name="MarketItem",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("canonical_key", models.CharField(max_length=200)),
                ("channel", models.CharField(max_length=10)),
                ("url", models.URLField(max_length=500)),
                ("creator", models.CharField(blank=True, max_length=200)),
                ("caption", models.TextField(blank=True)),
                ("published_at", models.DateTimeField(null=True)),
                ("metrics", models.JSONField(default=dict)),
                ("qualification", models.JSONField(default=dict)),
                ("classification", models.JSONField(default=dict)),
                ("classification_hash", models.CharField(blank=True, max_length=64)),
                ("preference", models.SmallIntegerField(default=0)),
                ("feedback_at", models.DateTimeField(null=True)),
                ("first_seen_at", models.DateTimeField(auto_now_add=True)),
                ("last_seen_at", models.DateTimeField()),
                ("company", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="market_items", to="engine.company")),
            ],
        ),
        migrations.CreateModel(
            name="MarketObservation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("provider_id", models.CharField(blank=True, max_length=200)),
                ("metrics", models.JSONField(default=dict)),
                ("observed_at", models.DateTimeField(auto_now_add=True)),
                ("item", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="observations", to="engine.marketitem")),
                ("request", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="engine.scraperequest")),
            ],
        ),
        migrations.AddConstraint(
            model_name="marketitem",
            constraint=models.UniqueConstraint(fields=("company", "canonical_key"), name="unique_company_market_item"),
        ),
        migrations.AddConstraint(
            model_name="marketobservation",
            constraint=models.UniqueConstraint(fields=("item", "request"), name="unique_market_observation"),
        ),
    ]
