# Generated by Django 5.2.17 on 2026-09-30 18:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0023_market_intelligence'),
    ]

    operations = [
        migrations.AddField(
            model_name='motionproject',
            name='sequence_settings',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='motionproject',
            name='source_sequence',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='film', to='engine.sequenceproject'),
        ),
        migrations.AddField(
            model_name='sequenceproject',
            name='source_run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sequences', to='engine.contentrun'),
        ),
    ]
