# Generated by Django 5.2.17 on 2026-10-02 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0024_motionproject_sequence_settings_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MotionWorkerSession',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('expires_at', models.DateTimeField()),
            ],
        ),
    ]
