# Generated by Django 5.2.17 on 2026-10-02 14:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0025_motion_worker_session'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssistantConversation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(default='Nytt samtal', max_length=160)),
                ('revision', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='engine.company')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='AssistantTurn',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('revision', models.PositiveIntegerField()),
                ('request', models.JSONField()),
                ('response', models.JSONField(default=dict)),
                ('usage', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('planning', 'Planerar'), ('completed', 'Klar'), ('failed', 'Misslyckades')], default='planning', max_length=12)),
                ('error', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(null=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turns', to='engine.assistantconversation')),
            ],
            options={
                'ordering': ['revision'],
            },
        ),
        migrations.CreateModel(
            name='AssistantPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('spec', models.JSONField()),
                ('fingerprint', models.CharField(max_length=64)),
                ('prepared', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('turn', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='plan', to='engine.assistantturn')),
            ],
        ),
        migrations.CreateModel(
            name='AssistantTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.SlugField(max_length=80)),
                ('version', models.PositiveIntegerField(default=1)),
                ('title', models.CharField(max_length=160)),
                ('instructions', models.TextField()),
                ('kind', models.CharField(default='auto', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assistant_templates', to='engine.company')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('company', 'key', 'version'), name='assistant_template_version')],
            },
        ),
        migrations.AddConstraint(
            model_name='assistantturn',
            constraint=models.UniqueConstraint(fields=('conversation', 'revision'), name='assistant_turn_revision'),
        ),
    ]
